name: Workshop
run-name: testing workflows 
on: [push]
jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - run: dotnet build
    - name: CodeQL Bundle
  # You may pin to the exact commit or the version.
  # uses: advanced-security/codeql-bundle-action@9437ba7f33c2a978c8897fb21b2a7e0809199d20
      uses: advanced-security/codeql-bundle-action@v1.1.0
     
         
            
